# Generated by Django 4.1.2 on 2022-10-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reviewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
