# Generated by Django 4.1.2 on 2022-10-18 12:17

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_message_reviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=50)),
                ('ov_bike', models.BooleanField()),
                ('elevator', models.BooleanField()),
                ('toilet', models.BooleanField()),
                ('park_and_ride', models.BooleanField()),
            ],
        ),
    ]
