# Generated by Django 4.1.2 on 2022-10-18 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='accounts.station'),
            preserve_default=False,
        ),
    ]
