# Generated by Django 4.1.2 on 2022-10-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_message_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='station',
        ),
    ]
