# Generated by Django 4.1.2 on 2022-10-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_message_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='station',
            field=models.CharField(default='8400621', max_length=8),
            preserve_default=False,
        ),
    ]
