# Generated by Django 4.1.2 on 2022-10-19 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_name_station_name_long_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.AddField(
            model_name='message',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
