# Generated by Django 4.1.2 on 2022-11-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_station_message_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
